Article:
   fields:
       title: varchar(50)
       text: text
   relations:
       Category: many
       Tag: many

Category:
   fields:
       title: varchar(50)
   relations:
       Article: many

Tag:
   fields:
       value: varchar(50)
   relations:
       Article: one